import { Metadata } from 'next';
import { BookOpen } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Glossary',
  description: 'Cryptocurrency and PayDeck terminology explained.',
};

export default function GlossaryPage() {
  return (
    <div className="max-w-4xl">
      {/* Hero Section */}
      <div className="mb-12">
        <div className="flex items-center gap-2 text-sm text-accent-600 dark:text-accent-dark-400 font-medium mb-4">
          <BookOpen className="w-4 h-4" />
          Reference
        </div>
        <h1 className="text-4xl md:text-5xl font-bold text-zinc-900 dark:text-white tracking-tight mb-6">
          Glossary
        </h1>
        <p className="text-xl text-zinc-600 dark:text-zinc-400 leading-relaxed">
          Cryptocurrency and PayDeck terminology explained.
        </p>
      </div>

      {/* Terms */}
      <div className="space-y-6">
        <Term 
          term="0-conf (Zero Confirmation)"
          definition="A transaction that has been broadcast to the network but not yet included in a block. Nexa uses double-spend proofs to make 0-conf transactions secure for most use cases."
        />
        
        <Term 
          term="Address"
          definition="A string of characters that represents a destination for cryptocurrency payments. Nexa addresses start with 'nexa:' followed by a CashAddr-encoded string."
        />
        
        <Term 
          term="BIP32"
          definition="Bitcoin Improvement Proposal 32. A standard for hierarchical deterministic (HD) wallets that allows deriving multiple keys from a single master seed."
        />
        
        <Term 
          term="BIP39"
          definition="Bitcoin Improvement Proposal 39. A standard for encoding cryptographic seeds as a list of words (typically 12 or 24 words), making them easier to write down and verify."
        />
        
        <Term 
          term="BIP44"
          definition="Bitcoin Improvement Proposal 44. A standard derivation path structure for HD wallets, defining how to organize accounts and addresses."
        />
        
        <Term 
          term="Block"
          definition="A collection of transactions bundled together and added to the blockchain. Nexa produces a new block approximately every 2 minutes."
        />
        
        <Term 
          term="Blockchain"
          definition="A distributed ledger that records all transactions in a cryptocurrency network. Each block contains a reference to the previous block, forming a chain."
        />
        
        <Term 
          term="CashAddr"
          definition="An address format used by Nexa (and Bitcoin Cash). Provides error detection and is case-insensitive."
        />
        
        <Term 
          term="Confirmation"
          definition="When a transaction is included in a block, it receives one confirmation. Each subsequent block adds another confirmation, making the transaction progressively harder to reverse."
        />
        
        <Term 
          term="Derivation Path"
          definition="The path used to derive keys from a master seed in an HD wallet. PayDeck uses m/44'/29223'/0'/0/n for Nexa."
        />
        
        <Term 
          term="Double-Spend"
          definition="An attack where someone attempts to spend the same coins twice. Nexa's double-spend proofs detect and prevent this before block confirmation."
        />
        
        <Term 
          term="Double-Spend Proof"
          definition="A cryptographic proof generated by Nexa nodes when a double-spend attempt is detected. This allows instant transaction security without waiting for block confirmation."
        />
        
        <Term 
          term="eFuse"
          definition="One-time programmable memory in the ESP32 chip. Once burned, eFuses cannot be reset. Used for secure boot and flash encryption keys in production mode."
        />
        
        <Term 
          term="Entropy"
          definition="Randomness used to generate cryptographic keys. Good entropy is essential for secure seed phrase generation. Sources include hardware random number generators and physical dice."
        />
        
        <Term 
          term="ESP32"
          definition="A microcontroller chip by Espressif with built-in WiFi and Bluetooth. PayDeck runs on the ESP32-WROOM-32 module."
        />
        
        <Term 
          term="Flash Encryption"
          definition="A security feature that encrypts all data stored in the ESP32's flash memory. Only available in secure build modes."
        />
        
        <Term 
          term="HD Wallet"
          definition="Hierarchical Deterministic wallet. A wallet that can generate unlimited addresses from a single seed phrase. All addresses are recoverable if you have the seed."
        />
        
        <Term 
          term="Mempool"
          definition="The pool of unconfirmed transactions waiting to be included in a block. Nodes broadcast transactions to the mempool before miners include them in blocks."
        />
        
        <Term 
          term="NEX"
          definition="The native cryptocurrency of the Nexa blockchain. Used for all payments in PayDeck."
        />
        
        <Term 
          term="Nexa"
          definition="A cryptocurrency focused on scalability and instant transactions. Uses double-spend proofs for secure 0-conf payments."
        />
        
        <Term 
          term="NVS (Non-Volatile Storage)"
          definition="Persistent storage on the ESP32 that survives power cycles. PayDeck stores settings, WiFi credentials, and wallet configuration in NVS."
        />
        
        <Term 
          term="PIN"
          definition="Personal Identification Number. A 6-digit code that protects access to PayDeck settings."
        />
        
        <Term 
          term="Private Key"
          definition="A secret number that allows spending cryptocurrency. PayDeck never stores private keys (watch-only wallet)."
        />
        
        <Term 
          term="Production Mode"
          definition="PayDeck's highest security configuration. Enables flash encryption and secure boot permanently. Cannot be reversed."
        />
        
        <Term 
          term="QR Code"
          definition="A two-dimensional barcode that encodes data like payment addresses and amounts. Customers scan QR codes with their wallet app to make payments."
        />
        
        <Term 
          term="Rostrum"
          definition="A Nexa blockchain indexing server. PayDeck connects to Rostrum servers to monitor addresses and detect incoming payments."
        />
        
        <Term 
          term="Secure Boot"
          definition="A security feature that verifies firmware signatures before running code. Prevents loading unauthorized firmware."
        />
        
        <Term 
          term="Seed Phrase"
          definition="A list of 12 (or 24) words that encode a cryptographic seed. Used to generate all keys in an HD wallet. Must be kept secret and backed up safely."
        />
        
        <Term 
          term="TLS (Transport Layer Security)"
          definition="Encryption protocol for secure communication over the internet. PayDeck uses TLS/WSS to connect to Rostrum servers."
        />
        
        <Term 
          term="Transaction"
          definition="A transfer of cryptocurrency from one address to another. Recorded permanently on the blockchain."
        />
        
        <Term 
          term="UTXO"
          definition="Unspent Transaction Output. The basic unit of value in Nexa (and Bitcoin). Each UTXO can only be spent once."
        />
        
        <Term 
          term="Watch-Only Wallet"
          definition="A wallet that can generate receiving addresses and monitor balances but cannot spend funds. PayDeck is watch-only for security."
        />
        
        <Term 
          term="WSS (WebSocket Secure)"
          definition="The secure version of the WebSocket protocol. PayDeck uses WSS to maintain a persistent, encrypted connection to Rostrum servers."
        />
        
        <Term 
          term="xPub (Extended Public Key)"
          definition="A special public key that can derive unlimited child public keys (addresses) without access to private keys. Used by PayDeck to generate receiving addresses."
        />
      </div>
    </div>
  );
}

// Component: Term
function Term({ term, definition }: { term: string; definition: string }) {
  return (
    <div className="pb-6 border-b border-zinc-200 dark:border-zinc-800 last:border-0">
      <dt className="text-lg font-semibold text-zinc-900 dark:text-white mb-2">{term}</dt>
      <dd className="text-zinc-600 dark:text-zinc-400">{definition}</dd>
    </div>
  );
}
